[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jobsearch-cli"
version = "1.0.0"
description = "A Python toolkit and CLI for searching, cleaning, and analyzing job market data using the SerpAPI Google Jobs API."
readme = "README.md"
<<<<<<< HEAD
requires-python = ">=3.9"
=======
requires-Python = ">=3.9"
>>>>>>> f2a308180d42de5841076ef6411d24ef4ebcfbe5
license = { text = "MIT" }

authors = [
    { name = "Logan", email = "logan416ah@gmail.com" }
]

<<<<<<< HEAD
dependencies = [
=======
dependecies = [
>>>>>>> f2a308180d42de5841076ef6411d24ef4ebcfbe5
    "requests",
    "pandas",
    "tqdm"
]

# INSTALLABLE CLI COMMAND
[project.scripts]
<<<<<<< HEAD
jobsearch = "jobsearch.cli:main"
=======
jobsearch = "jobsearch.cli:main"
>>>>>>> f2a308180d42de5841076ef6411d24ef4ebcfbe5
